// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartCaptureService():Promise<void>;

export function StopCaptureService():Promise<void>;
