// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartCaptureService() {
  return window['go']['main']['App']['StartCaptureService']();
}

export function StopCaptureService() {
  return window['go']['main']['App']['StopCaptureService']();
}
